services:
  fastapi:
    public: true
    image: karthik996/odesey-backend:latest
    build: .
    replicas: 2
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - 8080